name: CI/CD Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Чеккаут репозитория
      uses: actions/checkout@v3

    - name: Проверка структуры проекта
      run: |
        echo "Проверка наличия ключевых файлов в корне..."
        test -f index.html
        test -f Dockerfile
        test -f docker-compose.yml

    - name: Тестовая сборка Docker-образа
      run: |
        docker build -t spo-html-app:latest .
